server.port: 9090

jwt.authentication.secret: 1111
jwt.authentication.issuer: manki
jwt.authentication.audience: foo

public.key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8vvJ/RN5SbA1Nwq3kAyi
            EBHUPYLUGPhU65DHDElAE6XMB40/669vymSJIKmDJ7Q2X+HdJwFSoD5OVWzi3SuG
            Izwagu9JZAzHVFV6X1B65zP5wFGkeUVPueHWUEnUFRdHpig60I6DYVNaV2OX+VRI
            WnsPhQbr0GYsOP6fwpX+2Yh1h6GDB+pqVYSUi9KRkbrarZInwlo6M0vSde/ylxNy
            iRgAIahZgbc6XIqrl+nVvN06PwVGUWzQis3PsdManjyrzkw9SAZ0lXPCJt+08d1g
            JI5V1QqFk1L/tWqctfYRKTrE954ySMl1+h0GxTvzrQlH2vkFa4s6k5W8ZjKTp7JG
            GQIDAQAB

